<?xml version='1.0' encoding='UTF-8'?>
<robot name='rehab' xmlns:xacro='http://www.ros.org/wiki/xacro'>

<xacro:include filename='$(find rehab)/urdf/shoulder.urdf.xacro'/>
<xacro:include filename='$(find rehab)/urdf/elbow.urdf.xacro'/>
<xacro:include filename='$(find rehab)/urdf/wrist.urdf.xacro'/>
<xacro:include filename='$(find rehab)/urdf/hand.urdf.xacro'/>

<!-- Link dimensions -->
<!-- Base pole dimensions -->
<xacro:property name='polelen' value='2'/>
<xacro:property name='polerad' value='0.12'/>
<!-- Connecting base plate dimensions -->
<xacro:property name='basepllen' value='1.1'/>
<xacro:property name='basethick' value='0.05'/>
<xacro:property name='sh1len' value='0.25'/>
<!-- First motor dimensions -->
<xacro:property name='mot1rad' value='0.1'/>
<xacro:property name='mot1len' value='0.2'/>
<!-- Links for second motor -->
<xacro:property name='conn2len' value='0.45'/>
<xacro:property name='conn3len' value='0.4'/>
<!-- Second motor dimensions -->
<xacro:property name='mot2rad' value='0.1'/>
<xacro:property name='mot2len' value='0.2'/>
<!-- Third prismatic dimensions -->
<xacro:property name='prism3len' value='0.2'/>
<!-- Link for third motor -->
<xacro:property name='conn4len' value='0.4'/>
<!-- Third motor dimensions -->
<xacro:property name='mot3rad' value='0.08'/>
<xacro:property name='mot3len' value='0.12'/>
<!-- Shoulder interface dimensions -->
<xacro:property name='shintrad' value='0.15'/>
<xacro:property name='shintthick' value='0.05'/>

<!-- Elbow dimensions -->
<!-- Symmetric elbow connecting links dimensions -->
<xacro:property name='elcon1len' value='0.20'/>
<xacro:property name='elcon1width' value='0.1'/>
<xacro:property name='elcon1thick' value='0.04'/>
<!-- Symmetric elbow to forearm connecting links dimensions -->
<xacro:property name='elcon2len' value='0.15'/>
<xacro:property name='elcon2width' value='0.08'/>
<xacro:property name='elcon2thick' value='0.04'/>
<!-- Fourth motor dimensions -->
<xacro:property name='mot4rad' value='0.04'/>
<xacro:property name='mot4len' value='0.1'/>
<!-- Fourth prismatic dimensions -->
<xacro:property name='prism4len' value='0.1'/>
<xacro:property name='prism4width' value='0.05'/>
<xacro:property name='prism4thick' value='0.025'/>
<!-- Elbow interface dimensions -->
<xacro:property name='elintrad' value='0.12'/>
<xacro:property name='elintthick' value='0.03'/>
<!-- Fifth motor dimensions -->
<xacro:property name='mot5rad' value='0.04'/>
<xacro:property name='mot5len' value='0.1'/>

<!-- Wrist and hand dimensions -->
<!-- Wrist flexion/extension connecting link dimensions -->
<xacro:property name='wrcon1len' value='0.18'/>
<xacro:property name='wrcon1width' value='0.08'/>
<xacro:property name='wrcon1thick' value='0.04'/>
<!-- Sixth motor dimensions -->
<xacro:property name='mot6rad' value='0.03'/>
<xacro:property name='mot6len' value='0.1'/>
<!-- Wrist abduction/adduction connecting links dimensions -->
<xacro:property name='wrcon2len' value='0.18'/>
<xacro:property name='wrcon2width' value='0.08'/>
<xacro:property name='wrcon2thick' value='0.04'/>
<xacro:property name='wrcon3len' value='0.19'/>
<xacro:property name='wrcon3width' value='0.08'/>
<xacro:property name='wrcon3thick' value='0.04'/>
<!-- Seventh motor dimensions -->
<xacro:property name='mot7rad' value='0.03'/>
<xacro:property name='mot7len' value='0.1'/>
<!-- Compliant spherical joint dimensions -->
<xacro:property name='spherbaserad' value='0.03'/>
<xacro:property name='spherbaselen' value='0.03'/>
<xacro:property name='spherjntrad' value='0.012'/>
<xacro:property name='spherjntlen' value='0.02'/>
<!-- Connecting links for fifth prismatic joint -->
<xacro:property name='wrcon4thick' value='0.02'/>
<xacro:property name='wrcon4len' value='0.08'/>
<!-- Fifth prismatic dimensions -->
<xacro:property name='prism5len' value='0.08'/>
<xacro:property name='prism5width' value='0.05'/>
<xacro:property name='prism5thick' value='0.02'/>
<!-- Connecting links for eight motor dimensions -->
<xacro:property name='wrcon5thick' value='0.02'/>
<xacro:property name='wrcon5len' value='0.19'/>
<xacro:property name='wrcon5width' value='0.08'/>
<!-- Eight motor dimensions -->
<xacro:property name='mot8rad' value='0.025'/>
<xacro:property name='mot8len' value='0.1'/>
<!-- Hand grips dimensions -->
<xacro:property name='hngriprad' value='0.005'/>
<xacro:property name='hngriplen' value='0.15'/>


<!-- Material colors -->
<material name='red'>
  <color rgba='0.8 0 0 1'/>
</material>

<material name='green'>
  <color rgba='0 0.8 0 1'/>
</material>

<material name='blue'>
  <color rgba='0 0 0.8 1'/>
</material>

<material name='black'>
  <color rgba='0 0 0 1'/>
</material>

<material name='white'>
  <color rgba='1 1 1 1'/>
</material>

<material name='grey'>
  <color rgba='0.5 0.5 0.5 1'/>
</material>


<!-- Shoulder links and joints -->

<link name='base_link'>
  <visual>
    <geometry>
      <cylinder radius='${polerad}' length='${polelen}'/>
    </geometry>
    <origin rpy='0 0 0' xyz='0 0 ${polelen/2}'/>
    <material name='green'></material>
  </visual>
  <collision>
    <geometry>
      <cylinder radius='${polerad}' length='${polelen}'/>
    </geometry>
    <origin rpy='0 0 0' xyz='0 0 -${polelen/2}'/>
  </collision>
</link>

<!-- Plate connecting base to prismatic joints -->
<xacro:sh_link name='1' x='${basepllen/2-polerad*1.1}' z='${basethick/2}' material='blue'>
  <box size='${basepllen} 0.3 ${basethick}'/>
</xacro:sh_link>
<!-- Link for pismatic joint -->
<xacro:sh_link name='2' z='-${basethick/2}' material='grey'>
  <box size='${sh1len} ${sh1len} ${basethick}'/>
</xacro:sh_link>

<!-- Link for pismatic joint -->
<xacro:sh_link name='3' z='-${basethick/2}' material='grey'>
  <box size='${sh1len} ${sh1len} ${basethick}'/>
</xacro:sh_link>

<!-- Motor for first revolute joint -->
<xacro:sh_link name='4' z='-${mot1len/2}' material='black'>
  <cylinder radius='${mot1rad}' length='${mot1len}'/>
</xacro:sh_link>
<!-- Links for second revolute joint -->
<xacro:sh_link name='5' z='-${basethick/2}' y='-${conn2len/2-mot1rad*1.1}'>
  <box size='0.3 ${conn2len} ${basethick}'/>
</xacro:sh_link>
<xacro:sh_link name='6' z='-${conn3len/2}'>
  <box size='0.3 ${basethick} ${conn3len}'/>
</xacro:sh_link>
<!-- Motor for second revolute joint -->
<xacro:sh_link name='7' roll='${pi/2}' y='-${mot2len/2}' material='black'>
  <cylinder radius='${mot2rad}' length='${mot2len}'/>
</xacro:sh_link>
<!-- Third prismatic connection -->
<xacro:sh_link name='8' y='${basethick/2}' material='grey'>
  <box size='${prism3len} ${basethick} ${prism3len}'/>
</xacro:sh_link>
<xacro:sh_link name='9' z='-${conn4len/2-mot2rad*1.1}' y='${basethick/2}'>
  <box size='0.3 ${basethick} ${conn4len}'/>
</xacro:sh_link>
<!-- Motor for third revolute joint -->
<xacro:sh_link name='10' z='${mot3len/2}' material='black'>
  <cylinder radius='${mot3rad}' length='${mot3len}'/>
</xacro:sh_link>
<!-- Interface to human shoulder -->
<xacro:sh_link name='11' z='${shintthick/2}' material='grey'>
  <cylinder radius='${shintrad}' length='${shintthick}'/>
</xacro:sh_link>


<!-- First prismatic passive joint -->
<joint name='base_to_shoulder1' type='fixed'>
  <parent link='base_link'/>
  <child link='shoulder1'/>
  <origin rpy='0 0 -${pi/12}' xyz='0 0 ${polelen}'/>
</joint>

<!-- Base connecting plate to prismatic joint -->
<xacro:sh_joint parent='1' child='2' type='prismatic' x='${basepllen-polerad*1.1-sh1len/2}' axisy='1'>
</xacro:sh_joint>

<!-- Second prismatic passive joint -->
<xacro:sh_joint parent='2' child='3' type='prismatic' z='-${basethick}' axisx='1'>
</xacro:sh_joint>

<!-- Fixed joint between prismatic and revolute joint -->
<xacro:sh_joint parent='3' child='4' z='-${basethick}'>
</xacro:sh_joint>

<!-- First revolute active joint -->
<xacro:sh_joint parent='4' child='5' type='continuous' z='-${mot1len}' axisz='1'>
</xacro:sh_joint>
<xacro:sh_joint parent='5' child='6' y='-${conn2len-mot1rad*1.1+basethick/2}'>
</xacro:sh_joint>
<xacro:sh_joint parent='6' child='7' y='-${basethick/2}' z='-${conn3len-mot2rad*1.1}'>
</xacro:sh_joint>
<!-- Second revolute active joint -->
<xacro:sh_joint parent='7' child='8' type='continuous' y='${basethick}' axisy='1'>
</xacro:sh_joint>
<!-- Third prismatic passive joint -->
<xacro:sh_joint parent='8' child='9' type='prismatic' y='${basethick}' axisz='1'>
</xacro:sh_joint>
<xacro:sh_joint parent='9' child='10' z='-${conn4len-mot2rad*1.1}' y='-${mot3rad}'>
</xacro:sh_joint>
<!-- Shoulder interface fixed connection -->
<xacro:sh_joint parent='9' child='11' z='-${conn4len-mot2rad*1.1}' y='${basethick+shintrad}'>
</xacro:sh_joint>


<!-- Elbow links and joints -->

<!-- Shoulder to elbow two reflected links -->
<xacro:el_link name='1' z='-${elcon1len/2}' x='${shintrad-elcon1thick}' reflectx='-1'>
  <box size='${elcon1thick} ${elcon1width} ${elcon1len}'/>
</xacro:el_link>
<xacro:el_link name='2' z='-${elcon1len/2}' x='${shintrad-elcon1thick}' reflectx='1'>
  <box size='${elcon1thick} ${elcon1width} ${elcon1len}'/>
</xacro:el_link>
<!-- Elbow to forearm reflected links -->
<xacro:el_link name='3' z='-${elcon2len/2*0.9}' x='${shintrad-elcon1thick-elcon2thick}'
  reflectx='-1'>
  <box size='${elcon2thick} ${elcon2width} ${elcon2len}'/>
</xacro:el_link>
<xacro:el_link name='4' z='-${elcon2len/2*0.9}' x='${shintrad-elcon1thick-elcon2thick}'
  reflectx='1'>
  <box size='${elcon2thick} ${elcon2width} ${elcon2len}'/>
</xacro:el_link>
<!-- Motor for fourth revolute joint -->
<xacro:el_link name='5' pitch='${pi/2}' x='${mot4len/2}' material='black'>
  <cylinder radius='${mot4rad}' length='${mot4len}'/>
</xacro:el_link>
<!-- Fourth prismatic connections -->
<xacro:el_link name='6' x='${shintrad-elcon1thick-elcon2thick/2+prism4thick/2}'
  reflectx='-1' material='grey'>
  <box size='${prism4thick} ${prism4width} ${prism4len}'/>
</xacro:el_link>
<xacro:el_link name='7' x='${shintrad-elcon1thick-elcon2thick/2+prism4thick/2}'
  reflectx='1' material='grey'>
  <box size='${prism4thick} ${prism4width} ${prism4len}'/>
</xacro:el_link>
<!-- Interface to human elbow -->
<xacro:el_link name='8' z='-${elintthick/2}' material='grey'>
  <cylinder radius='${elintrad}' length='${elintthick}'/>
</xacro:el_link>
<!-- Motor for fifth revolute joint -->
<xacro:el_link name='9' material='black' z='${mot5len/2}'>
  <cylinder radius='${mot5rad}' length='${mot5len}'/>
</xacro:el_link>

<!-- Shoulder to elbow revolute joint -->
<xacro:el_cust_joint name='sh11_to_el1_rot' type='continuous'
  parent='shoulder11' child='elbow1' axisz='1'>
</xacro:el_cust_joint>
<xacro:el_cust_refl_joint name='sh11_to_el2_rot' type='continuous' mimic='sh11_to_el1_rot'
  parent='shoulder11' child='elbow2' axisz='1'>
</xacro:el_cust_refl_joint>
<!-- Elbow to forearm revolute joint -->
<xacro:el_joint parent='1' child='3' type='continuous' z='-${elcon1len*0.9}' axisx='1'>
</xacro:el_joint>
<xacro:el_refl_joint parent='2' child='4' type='continuous' mimic='el1_el3'
  z='-${elcon1len*0.9}' axisx='1'>
</xacro:el_refl_joint>
<!-- Fourth motor fixed connection -->
<xacro:el_joint parent='1' child='5' x='${shintrad-elcon1thick/2}' z='-${elcon1len*0.9}'>
</xacro:el_joint>
<!-- Fourth prismatic joint -->
<xacro:el_joint parent='3' child='6' type='prismatic' z='-${elcon2len*0.9}' axisz='1'>
</xacro:el_joint>
<xacro:el_refl_joint parent='4' child='7' type='prismatic' z='-${elcon2len*0.9}' axisz='1'
  mimic='el3_el6'>
</xacro:el_refl_joint>
<!-- Elbow interface fixed connection -->
<xacro:el_joint parent='6' child='8' z='-${prism4len/2}'>
</xacro:el_joint>
<!-- Fifth motor fixed connection -->
<xacro:el_joint parent='6' child='9' x='${elintrad+mot5rad}' z='-${prism4len/2+elintthick}'>
</xacro:el_joint>

<!-- Wrist and hand links and joints -->
<xacro:wr_link name='1' z='-${wrcon1len/2}' x='-${elintrad-wrcon1thick}'>
  <box size='${wrcon1thick} ${wrcon1width} ${wrcon1len}'/>
</xacro:wr_link>
<!-- Motor for sixth revolute joint -->
<xacro:wr_link name='2' material='black' pitch='${pi/2}' x='-${mot6len/2}'>
  <cylinder radius='${mot6rad}' length='${mot6len}'/>
</xacro:wr_link>
<!-- Connecting links for seventh revolute joint -->
<xacro:wr_link name='3' x='${wrcon2thick/2}' y='-${wrcon2len/2*0.8}'>
  <box size='${wrcon2thick} ${wrcon2len} ${wrcon2width}'/>
</xacro:wr_link>
<xacro:wr_link name='4' y='-${wrcon3thick/2}' x='${wrcon3len/2}'>
  <box size='${wrcon3len} ${wrcon3thick} ${wrcon3width}'/>
</xacro:wr_link>
<!-- Motor for seventh revolute joint -->
<xacro:wr_link name='5' material='black' roll='${pi/2}' y='-${mot7len/2}'>
  <cylinder radius='${mot7rad}' length='${mot7len}'/>
</xacro:wr_link>
<!-- Links for spherical joint -->
<xacro:wr_link name='6' material='white' y='${spherbaserad}'>
  <cylinder radius='${spherbaserad}' length='${spherbaselen}'/>
</xacro:wr_link>
<xacro:wr_link name='7' material='white' z='${spherjntlen/2}'>
  <cylinder radius='${spherjntrad}' length='${spherjntlen}'/>
</xacro:wr_link>
<xacro:wr_link name='8' material='white' z='-${spherjntlen/2}'>
  <cylinder radius='${spherjntrad}' length='${spherjntlen}'/>
</xacro:wr_link>
<xacro:wr_link name='9' material='white'>
  <cylinder radius='${spherbaserad}' length='${spherbaselen}'/>
</xacro:wr_link>
<!-- Connecting links for prismatic joint -->
<xacro:wr_link name='10'>
  <box size='${spherbaserad*2.2} ${spherbaserad*2.2} ${wrcon4thick}'/>
</xacro:wr_link>
<xacro:wr_link name='11'>
  <box size='${wrcon4thick} ${spherbaserad*2.2} ${wrcon4len}'/>
</xacro:wr_link>
<!-- Fifth prismatic link -->
<xacro:wr_link name='12' material='grey'>
  <box size='${prism5thick} ${prism5width} ${prism5len}'/>
</xacro:wr_link>
<!-- Connecting links for eight motor -->
<xacro:wr_link name='13' x='${wrcon5thick/2}'>
  <box size='${wrcon5thick} ${wrcon5len} ${wrcon5width}'/>
</xacro:wr_link>
<!-- Motor for eight revolute joint -->
<xacro:wr_link name='14' material='black' pitch='${pi/2}' x='${mot8len/2}'>
  <cylinder radius='${mot8rad}' length='${mot8len}'/>
</xacro:wr_link>
<!-- Hand interaction device -->


<!-- Elbow to wrist revolute joint -->
<xacro:wr_cust_joint name='el8_to_wr1_rot' type='continuous' z='-${elintthick}'
  parent='elbow8' child='wrist1' axisz='1'>
</xacro:wr_cust_joint>
<!-- Sixth motor fixed connection -->
<xacro:wr_joint parent='1' child='2' x='-${elintrad-wrcon1thick/2}'
  z='-${wrcon1len*0.9-mot6rad}'>
</xacro:wr_joint>
<!-- Wrist flexion/extension (sixth) revolute joint -->
<xacro:wr_joint parent='1' child='3' type='continuous' x='-${elintrad-wrcon1thick*3/2}'
  z='-${wrcon1len*0.9-mot6rad}' axisx='1'>
</xacro:wr_joint>
<xacro:wr_joint parent='3' child='4' y='-${wrcon2len/2*(0.8+1)}'>
</xacro:wr_joint>
<!-- Seventh motor fixed connection -->
<xacro:wr_joint parent='4' child='5' x='${wrcon3len*0.9-mot7rad}'
  y='-${wrcon3thick}'>
</xacro:wr_joint>
<!-- Spherical joint as compliant mechanism -->
<xacro:wr_joint parent='4' child='6' type='continuous' x='${wrcon3len*0.9-mot7rad}'
  axisy='1'>
</xacro:wr_joint>
<xacro:wr_joint parent='6' child='7' y='${spherbaserad}' z='-${spherbaselen/2+spherjntlen}'>
</xacro:wr_joint>
<xacro:wr_spher_joint parent='7' child='8'>
</xacro:wr_spher_joint>
<xacro:wr_joint parent='8' child='9' z='-${spherbaselen/2+spherjntlen}'>
</xacro:wr_joint>
<!-- Fifth prismatic joint and connecting elements -->
<xacro:wr_joint parent='9' child='10' z='-${spherbaselen/2+wrcon4thick/2}'>
</xacro:wr_joint>
<xacro:wr_joint parent='10' child='11' x='${spherbaserad*2.2/2+wrcon4thick/2}'
  z='-${wrcon4len/2-wrcon4thick/2}'>
</xacro:wr_joint>
<xacro:wr_joint parent='11' child='12' type='prismatic' x='${wrcon4thick/2+prism5thick/2}'
  z='-${wrcon4len/2}' axisz='1'>
</xacro:wr_joint>
<!-- Eight revolute joint connection and motor fixed links -->
<xacro:wr_joint parent='12' child='13' x='${prism5thick/2}' y='${wrcon5len/2*0.7}'>
</xacro:wr_joint>
<xacro:wr_joint parent='13' child='14' x='${wrcon5thick}' y='${wrcon5len/2*0.9-mot8rad}'>
</xacro:wr_joint>
<!-- Eight revolute joint hand interaction -->
<xacro:hand_interaction rad='${hngriprad}' len='${hngriplen}' parent='wrist13'
  transl='${wrcon5len/2*0.9-mot8rad}'/>

</robot>
