# Prismatic grasping
dependent_joints:
  ThumbTMC_FE_joint: {parent: ThumbMCP_joint, factor: 1.1, offset: -0.785398}
  ThumbIP_joint: {parent: ThumbMCP_joint, factor: 0.83333333}
  IndexCMC_joint: {parent: MiddleCMC_joint, factor: 1.0}
  IndexPIP_joint: {parent: IndexMCP_FE_joint, factor: 0.66666667}
  IndexDIP_joint: {parent: IndexMCP_FE_joint, factor: 0.33333333}
  MiddleCMC_joint: {parent: RingCMC_joint, factor: 0.5}
  MiddleMCP_AA_joint: {parent: IndexMCP_AA_joint, factor: 0.2}
  MiddlePIP_joint: {parent: MiddleMCP_FE_joint, factor: 0.66666667}
  MiddleDIP_joint: {parent: MiddleMCP_FE_joint, factor: 0.33333333}
  RingCMC_joint: {parent: LittleCMC_joint, factor: 0.66666667}
  RingMCP_AA_joint: {parent: LittleMCP_AA_joint, factor: 0.5}
  RingPIP_joint: {parent: RingMCP_FE_joint, factor: 0.75}
  RingDIP_joint: {parent: RingMCP_FE_joint, factor: 0.5}
  LittlePIP_joint: {parent: LittleMCP_FE_joint, factor: 0.75}
  LittleDIP_joint: {parent: LittleMCP_FE_joint, factor: 0.5}
